dotenv: .env

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.1"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

networks:
  development:
    verify: False
    key_hash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 10000000000000000
  rinkeby:
    verify: True
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    key_hash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000

wallets:
  from_key1: ${PRIVATE_KEY1}
  from_key3: ${PRIVATE_KEY3}